name: Hello World compsite 
on:
  push:
    branches: [ main ]
    paths: [ hello-world-composite-action/** ]
  workflow_dispatch:

jobs:
  Hello-World_compsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - id: foo
        uses: rob-bankers/my-first-action@7f2f1c07b9022b0f3ac457c58a061e72f928e95e
        with:
          who-to-greet: 'Bankers'
