name: Hello World compsite 
on:
  push:
    branches: [ main ]
    paths: [ hello-world-composite-action/** ]
  workflow_dispatch:

jobs:
  Hello-World_compsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - id: foo
        uses: rob-bankers/my-first-action@2e6f4ec405f629735b85defd29bdd0cb5c80307a
        with:
          who-to-greet: 'Bankers'
